#!/bin/bash

set -e

function --diff { git diff --cached "$@"; }
function --n-changes { --name-only | wc -l | xargs echo; }
function --name-only { --diff --name-only; }
function --name-status { --diff --name-status; }
function --normalize-space { xargs echo; }
function --shortstat { --diff --shortstat; }
function --stat { --diff --stat=45 | sed \$d; }

function --simple-summary {
  if [[ `--stat` ]]; then
    --name-status | sed "s'`--name-only`'`--stat`'"
  else
    --name-status
  fi | --normalize-space
}

case `--n-changes` in
  0) ;;
  1) --simple-summary ;;
  *) --shortstat ;;
esac
