#!/bin/bash

set -e

diff_args=("$@")

function --diff { git diff "${diff_args[@]}" "$@"; }
function --n-changes { --name-only | wc -l | xargs echo; }
function --name-only { --diff --name-only; }
function --name-status { --diff --name-status; }
function --normalize-space { xargs echo; }
function --shortstat { --diff --shortstat; }
function --stat { --diff --stat=60 | sed \$d; }
function --status-only { --name-status | awk '{print $1}'; }

function --simple-summary {
  if [[ `--stat` ]]; then
    echo `--status-only` `--stat`
  else
    --name-status | --normalize-space
  fi
}

case `--n-changes` in
  0) ;;
  1) --simple-summary ;;
  *) --shortstat ;;
esac
